/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppReceiveRouteImport } from './routes/_app/receive'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSwapRouteImport } from './routes/_app/swap'
import { Route as AppAssetIdRouteImport } from './routes/_app/asset.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetIdRoute = AppAssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/receive': typeof AppReceiveRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/swap': typeof AppSwapRoute
  '/asset/$id': typeof AppAssetIdRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AppActivityRoute
  '/receive': typeof AppReceiveRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/swap': typeof AppSwapRoute
  '/': typeof AppIndexRoute
  '/asset/$id': typeof AppAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/receive': typeof AppReceiveRoute
  '/_app/send': typeof AppSendRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/swap': typeof AppSwapRoute
  '/_app/': typeof AppIndexRoute
  '/_app/asset/$id': typeof AppAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/receive'
    | '/send'
    | '/settings'
    | '/swap'
    | '/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/receive'
    | '/send'
    | '/settings'
    | '/swap'
    | '/'
    | '/asset/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/activity'
    | '/_app/receive'
    | '/_app/send'
    | '/_app/settings'
    | '/_app/swap'
    | '/_app/'
    | '/_app/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive': {
      id: '/_app/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/swap': {
      id: '/_app/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asset/$id': {
      id: '/_app/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AppAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppSendRoute: typeof AppSendRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSwapRoute: typeof AppSwapRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetIdRoute: typeof AppAssetIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppSendRoute: AppSendRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSwapRoute: AppSwapRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetIdRoute: AppAssetIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
